/*
 * This source file was generated by the Gradle 'init' task
 */
package org.nacha;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
        // testing of App.java


}
