/*
 * This source file was generated by the Gradle 'init' task
 */
package org.nacha;

import  org.nacha.domain.Payments;
public class App {
    public static void main(String[] args) {
        Payments p1 = new Payments();
        p1.showBanner();
    }
}
