/*
 * This source file was generated by the Gradle 'init' task
 */
package org.nacha;

public class App {
    public static void main(String[] args) {
        org.nacha.domain.Payment p1 = new org.nacha.domain.Payment();
        p1.showBanner();
    }
}
