/*
 * This source file was generated by the Gradle 'init' task
 */
package org.nacha;
import org.nacha.api.PaymentController;

public class App {


    public static void main(String[] args) {
        PaymentController p1 = new org.nacha.api.PaymentController();
        System.out.println(p1.getPayment(668_0763_053L));

    }
}
